[package]
authors = ["Anthony Dodd <Dodd.AnthonyJosiah@gmail.com>"]
categories = ["database", "data-structures"]
description = "An ODM for MongoDB built upon the mongo rust driver."
documentation = "https://github.com/thedodd/wither"
exclude = [".git*", "target", "docker-compose.yml", "Dockerfile"]
homepage = "https://github.com/thedodd/wither"
keywords = ["mongodb", "odm", "orm"]
license = "Apache-2.0"
name = "wither"
readme = "README.md"
repository = "https://github.com/thedodd/wither"
version = "0.5.2"

[dependencies]
bson = "^0.12.0"
chrono = "^0.4.0"
log = "^0.4.0"
mongodb = { git = "https://github.com/tobz1000/mongo-rust-driver-prototype.git" }
serde = "^1.0.0"
serde_derive = "1.0.0"

[dev-dependencies]
lazy_static = "<1.0"
